# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods's specs repository is huge and slow. Get specs from Gitlab CI by default.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "\"#{generated_xcode_build_settings_path}\" must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first."
  end

  File.read(generated_xcode_build_settings_path).each_line do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
  raise 'FLUTTER_ROOT not found in Generated.xcconfig. Try running \"flutter pub get\" again.'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! # This is needed for some packages
  use_modular_headers!

    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # AdMobend
  # AdMob Mediation: Meta Audience Network adapter
  # Ref: https://developers.google.com/admob/ios/mediation/meta
  pod 'GoogleMobileAdsMediationFacebook'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
