import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class MigrateUsernames {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Mevcut tüm kullanıcıları kontrol et ve kullanıcı adı olmayanları güncelle
  static Future<void> migrateAllUsers() async {
    try {
      debugPrint('🔄 [MIGRATION] Kullanıcı adı migration başlatılıyor...');
      
      // Tüm kullanıcıları al
      final usersSnapshot = await _firestore.collection('users').get();
      
      int migratedCount = 0;
      int skippedCount = 0;
      
      for (final doc in usersSnapshot.docs) {
        final data = doc.data();
        final username = data['username'] as String?;
        
        // Kullanıcı adı yoksa otomatik oluştur
        if (username == null || username.isEmpty) {
          final autoUsername = await _generateUniqueUsernameForUser(doc.id);
          
          await doc.reference.update({
            'username': autoUsername,
            'usernameChanged': false, // Henüz değiştirilmedi
            'autoGenerated': true, // Otomatik oluşturuldu
            'migratedAt': FieldValue.serverTimestamp(),
          });
          
          migratedCount++;
          debugPrint('✅ [MIGRATION] Kullanıcı ${doc.id} için kullanıcı adı atandı: $autoUsername');
        } else {
          skippedCount++;
          debugPrint('ℹ️ [MIGRATION] Kullanıcı ${doc.id} zaten kullanıcı adına sahip: $username');
        }
      }
      
      debugPrint('✅ [MIGRATION] Migration tamamlandı!');
      debugPrint('📊 [MIGRATION] Güncellenen: $migratedCount, Atlanan: $skippedCount');
    } catch (e) {
      debugPrint('❌ [MIGRATION] Migration hatası: $e');
    }
  }

  /// Belirli bir kullanıcı için benzersiz kullanıcı adı oluştur
  static Future<String> _generateUniqueUsernameForUser(String userId) async {
    try {
      // Rastgele sayı oluştur
      final random = (100 + (DateTime.now().millisecondsSinceEpoch % 899900)).toString();
      String baseUsername = 'kullanıcı$random';
      String username = baseUsername;
      int counter = 1;
      
      // Benzersizliği kontrol et
      while (true) {
        final existingUser = await _firestore
            .collection('users')
            .where('username', isEqualTo: username)
            .limit(1)
            .get();
        
        if (existingUser.docs.isEmpty) {
          return username;
        }
        
        // Çakışma varsa sayı ekle
        username = '$baseUsername$counter';
        counter++;
        
        if (counter > 100) {
          // Çok fazla deneme yapıldıysa rastgele numara kullan
          final random = DateTime.now().millisecondsSinceEpoch % 1000000;
          return 'kullanıcı$random';
        }
      }
    } catch (e) {
      debugPrint('❌ [MIGRATION] Kullanıcı adı oluşturma hatası: $e');
      // Hata durumunda timestamp kullan
      return 'kullanıcı${DateTime.now().millisecondsSinceEpoch % 1000000}';
    }
  }
  
  /// Tek bir kullanıcıyı kontrol et ve gerekirse güncelle
  static Future<void> checkAndMigrateUser(String userId) async {
    try {
      final userDoc = await _firestore.collection('users').doc(userId).get();
      
      if (!userDoc.exists) {
        debugPrint('⚠️ [MIGRATION] Kullanıcı belgesi bulunamadı: $userId');
        return;
      }
      
      final data = userDoc.data()!;
      final username = data['username'] as String?;
      
      // Kullanıcı adı yoksa otomatik oluştur
      if (username == null || username.isEmpty) {
        final autoUsername = await _generateUniqueUsernameForUser(userId);
        
        await userDoc.reference.set({
          'username': autoUsername,
          'usernameChanged': false, // Henüz değiştirilmedi
          'autoGenerated': true, // Otomatik oluşturuldu
          'migratedAt': FieldValue.serverTimestamp(),
        }, SetOptions(merge: true));
        
        debugPrint('✅ [MIGRATION] Kullanıcı $userId için kullanıcı adı atandı: $autoUsername');
      } else {
        debugPrint('ℹ️ [MIGRATION] Kullanıcı $userId zaten kullanıcı adına sahip: $username');
      }
    } catch (e) {
      debugPrint('❌ [MIGRATION] Kullanıcı migration hatası: $e');
    }
  }
}
